.TH esearch 1 "13 Février 2005" "esync" ""

.SH "NAME"
esync \- Appelle 'emerge \-\-sync' et 'eupdatedb' et affiche les mises à jour

.SH "SYNOPSIS"
.B esync
[ options ]

.SH "DESCRIPTION"
esync importe d'abord l'ancien index de recherche, puis appelle 'emerge \-\-sync'
(ou une autre commande : voir les options) et 'eupdatedb'. Enfin il affiche
les nouveaux paquets ainsi que les paquets mis à jour.

.SH "OPTIONS"
.TP
.B \-\-help, \-h
Affiche le message d'aide
.TP
.B \-\-webrsync, \-w
Utilise 'emerge\-webrsync' au lieu de 'emerge \-\-sync'
.TP
.B \-\-delta-webrsync, \-d
Utilise 'emerge-delta-webrsync' au lieu de 'emerge --sync'
.TP
.B \-\-metadata, \-m
Utilise 'emerge \-\-metadata' au lieu de 'emerge \-\-sync'
.TP
.B \-\-layman\-sync, \-l
Utilise layman pour synchroniser tous les overlays installés, puis
synchronise l'arbre principal.
.TP
.B \-\-nocolor, \-n
Ne pas utiliser de codes ANSI pour l'affichage coloré
.TP
.B  \-\-quiet, \-q
Rend la sortie moins verbeuse (implique \-\-nospinner)
.TP
.B \-\-verbose, \-v
Rend la sortie plus verbeuse
.TP
.B \-\-nospinner, \-s
N'affiche pas le compteur d'index restant

.SH "VOIR AUSSI"
esearch(1), eupdatedb(1), emerge(1)

.SH "BUGS"
Pas de bugs connus

.SH "AUTEUR"
David Peter <davidpeter@web.de>
