.TH esearch 1 "13 Février 2005" "eupdatedb"

.SH "NAME"
esearch \- Met à jour l'index de recherche d'esearch

.SH "SYNOPSIS"
.B eupdatedb
[ options ]

.SH "DESCRIPTION"
eupdatedb génère le fichier d'index d'esearch. Vous devez
appeler eupdatedb pour faire en sorte que vos résultats de
recherches restent pertinents.

.SH "OPTIONS"
.TP
.B \-\-help, \-h
Affiche le message d'aide
.TP
.B \-\-verbose, \-v
Mode verbeux, montre les catégories
.TP
.B \-\-quiet, \-q
Affiche seulement un résumé
.TP
.B \-\-directory=dir, \-d dir
Charge l'index d'esearch depuis dir
.TP
.B \-\-nocolor, \-n
Ne pas utiliser de codes ANSI pour l'affichage coloré

.SH "VOIR AUSSI"
esearch(1), esync(1), emerge(1)

.SH "BUGS"
Pas de bugs connus

.SH "AUTEUR"
David Peter <davidpeter@web.de>
