.TH esearch 1 "Février 13, 2005" "eupdatedb"

.SH "NOM"
eupdatedb \- Met à jour la base de données d'indexation d'esearch

.SH "SYNOPSIS"
.B eupdatedb
[Options]

.SH "DESCRIPTION"
eupdatedb met à jour le fichier d'indexation utilisé par esearch.

.SH "OPTIONS"
.TP
.B \-\-help, \-h
Aide
.TP
.B \-\-verbose, \-v
Mode verbeux, affiche les catégories
.TP
.B \-\-quiet, \-q
Mode succinct, n'affiche que le sommaire
.TP
.B \-\-directory = dir, \-d dir
esearch lit le fichier d'indexation à partir de ce répertoire
.TP
.B \-\-nocolor, \-n
N'utilise pas de codes ANSI pour la sortie

.SH "VOIR AUSSI"
esearch(1), esync(1), emerge(1)

.SH "BUGS"
Pas de bugs connus

.SH "AUTEUR"
<davidpeter@web.de> Peter David
